<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/profile_completion.php';
require_once __DIR__ . '/../lib/analytics_capacity.php';
require_once __DIR__ . '/../lib/work_functions.php';
require_once __DIR__ . '/../lib/department_teams.php';
require_once __DIR__ . '/../lib/locations.php';

auth_required(['admin','supervisor']); refresh_current_user($pdo); cas_require_profile_completion($pdo); ensure_location_schema($pdo);
$locale=ensure_locale(); $t=load_lang($locale); $cfg=get_site_config($pdo); $me=current_user(); $yearNow=(int)date('Y');
$questionnaires=$pdo->query("SELECT id,title FROM questionnaire WHERE status<>'inactive' ORDER BY title")->fetchAll(PDO::FETCH_ASSOC)?:[];
$filters=analytics_capacity_normalize_filters(['year'=>$_GET['year']??$yearNow,'questionnaire_id'=>$_GET['questionnaire_id']??0,'department'=>$_GET['department']??'','team'=>$_GET['team']??'','work_function'=>$_GET['work_function']??'']);
if($filters['questionnaire_id']<=0&&$questionnaires)$filters['questionnaire_id']=(int)$questionnaires[0]['id']; $selectedLocation=max(0,(int)($_GET['location_id']??0));
$departments=department_options($pdo); $workFunctions=work_function_choices($pdo); $teamOptions=[]; $catalog=department_team_catalog($pdo);
foreach($catalog as $v){if(is_array($v)&&isset($v['slug'])){$teamOptions[(string)$v['slug']]=(string)($v['label']??$v['slug']);}elseif(is_array($v)){foreach($v as $team){if(is_array($team)&&!empty($team['slug']))$teamOptions[(string)$team['slug']]=(string)($team['label']??$team['slug']);}}}
$locations=location_records($pdo,false); $locationById=location_map_by_id($pdo,false);
$scope=analytics_capacity_latest_per_employee(analytics_capacity_fetch_response_rows($pdo,$filters,true,true)); $userLoc=[];$ids=array_values(array_unique(array_filter(array_map(fn($r)=>(int)($r['user_id']??0),$scope))));
if($ids){$s=$pdo->prepare('SELECT id,location_id FROM users WHERE id IN ('.implode(',',array_fill(0,count($ids),'?')).')');$s->execute($ids);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $r)$userLoc[(int)$r['id']]=(int)($r['location_id']??0);}
$rows=[];$unassigned=0;foreach($scope as $r){$lid=$userLoc[(int)$r['user_id']]??0;if(!$lid)$unassigned++;if($selectedLocation&&$lid!==$selectedLocation)continue;$r['location_id']=$lid;$rows[]=$r;}
$assigned=[];$sql="SELECT location_id,COUNT(*) c FROM users WHERE role='staff' AND account_status='active'";$params=[];
foreach([['department','department'],['team','cadre'],['work_function','work_function']] as [$fk,$col]){if($filters[$fk]!==''){$sql.=" AND $col=?";$params[]=$filters[$fk];}} if($selectedLocation){$sql.=' AND location_id=?';$params[]=$selectedLocation;} $sql.=' GROUP BY location_id';
$s=$pdo->prepare($sql);$s->execute($params);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $r)$assigned[(int)($r['location_id']??0)]=(int)$r['c'];
$group=[];foreach($rows as $r){$lid=(int)$r['location_id'];if($lid)$group[$lid][]=$r;}
$metrics=[];$points=[];$missing=[];foreach($locations as $l){$lid=(int)$l['id'];if($selectedLocation&&$lid!==$selectedLocation)continue;$data=$group[$lid]??[];if((int)$l['is_active']!==1&&!$data)continue;$att=analytics_capacity_attainment($data);$avg=analytics_capacity_average($data);$m=['id'=>$lid,'name'=>$l['name'],'region'=>$l['administrative_region'],'address'=>$l['physical_address'],'active'=>(int)$l['is_active']===1,'verification'=>$l['verification_status'],'assigned'=>$assigned[$lid]??0,'assessed'=>$att['total'],'hit'=>$att['hit'],'attainment'=>$att['percent'],'average'=>$avg];$metrics[]=$m;$lat=location_coordinate_value($l['latitude']);$lon=location_coordinate_value($l['longitude']);if($lat===null||$lon===null){if((int)$l['is_active']===1)$missing[]=$l['name'];continue;}$points[]=$m+['lat'=>$lat,'lon'=>$lon];}
usort($metrics,function($a,$b)use($locationById){$ta=$locationById[$a['id']]['location_type']??'';$tb=$locationById[$b['id']]['location_type']??'';if($ta==='hq'&&$tb!=='hq')return -1;if($tb==='hq'&&$ta!=='hq')return 1;return strcasecmp($a['name'],$b['name']);});
$overallAvg=analytics_capacity_average($rows);$overallAtt=analytics_capacity_attainment($rows);$activeCount=count(array_filter($locations,fn($l)=>(int)$l['is_active']===1));$mapped=count($points);
$qTitle='';foreach($questionnaires as $q)if((int)$q['id']===$filters['questionnaire_id']){$qTitle=(string)$q['title'];break;}
$query=array_filter(['year'=>$filters['year'],'questionnaire_id'=>$filters['questionnaire_id'],'department'=>$filters['department'],'team'=>$filters['team'],'work_function'=>$filters['work_function'],'location_id'=>$selectedLocation],fn($v)=>$v!==''&&$v!==0);
$baseQuery=$query;unset($baseQuery['location_id']);$leafletCss='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';$leafletJs='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';
?>
<!doctype html><html lang="<?=htmlspecialchars($locale,ENT_QUOTES,'UTF-8')?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Locations & GIS Analytics</title><link rel="stylesheet" href="<?=asset_url('assets/css/material.css')?>"><link rel="stylesheet" href="<?=asset_url('assets/css/styles.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars($leafletCss,ENT_QUOTES,'UTF-8')?>">
<style nonce="<?=htmlspecialchars(csp_nonce(),ENT_QUOTES,'UTF-8')?>">:root{--b:#1565c0}.gis-page{max-width:1500px;margin:auto;padding:1rem}.gis-head{display:flex;justify-content:space-between;gap:1rem}.gis-head h1{margin:0;color:#10233f}.analytics-tabs{display:flex;gap:.25rem;border-bottom:1px solid #d9e1ec;margin:1rem 0;overflow:auto}.analytics-tabs a{padding:.7rem .9rem;text-decoration:none;color:#2d3748;border-bottom:3px solid transparent;white-space:nowrap;font-weight:600}.analytics-tabs a.is-active{color:var(--b);border-bottom-color:var(--b)}.filters{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr)) auto;gap:.6rem;align-items:end}.filters label{display:flex;flex-direction:column;gap:.25rem;font-size:.8rem;font-weight:600}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:.8rem;margin:1rem 0}.kpi,.card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:1rem;box-shadow:0 2px 8px rgba(15,35,60,.06)}.kpi small{display:block;color:#687386;text-transform:uppercase}.kpi strong{font-size:1.7rem;color:#14345c}.grid{display:grid;grid-template-columns:8fr 4fr;gap:1rem}.map{height:560px;border:1px solid #dce4ed;border-radius:10px}.card h2{margin:0 0 .5rem;color:#0d47a1;font-size:1.05rem}.full{grid-column:1/-1}.note{border-left:4px solid #ef6c00;background:#fff8ed;padding:.7rem;margin:.7rem 0;font-size:.82rem}.table-wrap{overflow:auto}.tbl{width:100%;border-collapse:collapse;font-size:.83rem}.tbl th,.tbl td{padding:.52rem;border-bottom:1px solid #e7edf4;text-align:left}.tbl th{background:#f8fafc}.pill{display:inline-block;min-width:58px;text-align:center;padding:.2rem .4rem;border-radius:6px;font-weight:700}.good{background:#e8f5e9;color:#1b5e20}.mid{background:#fff8e1;color:#8d6e00}.low{background:#fff3e0;color:#e65100}.crit{background:#ffebee;color:#b71c1c}.empty{background:#f3f4f6;color:#6b7280}@media(max-width:1100px){.filters{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.full{grid-column:auto}.kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.filters,.kpis{grid-template-columns:1fr}.map{height:400px}}</style></head>
<body class="<?=htmlspecialchars(site_body_classes($cfg),ENT_QUOTES,'UTF-8')?>"><?php include __DIR__.'/../templates/header.php'; ?><main class="gis-page"><div class="gis-head"><div><h1>Locations & GIS Analytics</h1><p><?=htmlspecialchars($qTitle,ENT_QUOTES,'UTF-8')?> · <?=$filters['year']?>. Average score and ≥80% attainment are separate indicators.</p></div><div><button class="md-button md-outline" onclick="window.print()">Print / Save PDF</button><?php if(($me['role']??'')==='admin'):?><a class="md-button md-outline" href="<?=htmlspecialchars(url_for('admin/locations.php'),ENT_QUOTES,'UTF-8')?>">Manage Locations</a><?php endif;?></div></div>
<nav class="analytics-tabs"><a href="<?=htmlspecialchars(url_for('admin/analytics_dashboard.php').'?'.http_build_query($baseQuery),ENT_QUOTES,'UTF-8')?>">Overview</a><a href="<?=htmlspecialchars(url_for('admin/analytics_capacity.php').'?'.http_build_query($baseQuery),ENT_QUOTES,'UTF-8')?>">Capacity Areas & Gaps</a><a class="is-active" href="<?=htmlspecialchars(url_for('admin/analytics_locations.php').'?'.http_build_query($query),ENT_QUOTES,'UTF-8')?>">Locations & GIS</a><a href="<?=htmlspecialchars(url_for('admin/analytics.php?view=drilldown&questionnaire_id='.(int)$filters['questionnaire_id']),ENT_QUOTES,'UTF-8')?>">Questionnaire Analysis</a><a href="<?=htmlspecialchars(url_for('admin/course_mappings.php'),ENT_QUOTES,'UTF-8')?>">Learning Recommendations</a></nav>
<form method="get" class="filters"><label>Year<input type="number" min="2000" max="2100" name="year" value="<?=$filters['year']?>"></label><label>Questionnaire<select name="questionnaire_id"><?php foreach($questionnaires as $q):$qid=(int)$q['id'];?><option value="<?=$qid?>" <?=$filters['questionnaire_id']===$qid?'selected':''?>><?=htmlspecialchars($q['title'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Directorate<select name="department"><option value="">All</option><?php foreach($departments as $v=>$lab):?><option value="<?=htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8')?>" <?=$filters['department']===(string)$v?'selected':''?>><?=htmlspecialchars((string)$lab,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Team<select name="team"><option value="">All</option><?php foreach($teamOptions as $v=>$lab):?><option value="<?=htmlspecialchars($v,ENT_QUOTES,'UTF-8')?>" <?=$filters['team']===$v?'selected':''?>><?=htmlspecialchars($lab,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Work Role<select name="work_function"><option value="">All</option><?php foreach($workFunctions as $v=>$lab):?><option value="<?=htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8')?>" <?=$filters['work_function']===(string)$v?'selected':''?>><?=htmlspecialchars((string)$lab,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Work Location<select name="location_id"><option value="0">All Locations</option><?php foreach($locations as $l):$lid=(int)$l['id'];?><option value="<?=$lid?>" <?=$selectedLocation===$lid?'selected':''?>><?=htmlspecialchars($l['name'].((int)$l['is_active']===1?'':' (inactive)'),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><button class="md-button md-primary">Apply</button></form>
<div class="kpis"><div class="kpi"><small>Average Score</small><strong><?=$overallAvg!==null?number_format($overallAvg,1).'%':'—'?></strong></div><div class="kpi"><small>Staff ≥80%</small><strong><?=$overallAtt['percent']!==null?number_format((float)$overallAtt['percent'],1).'%':'—'?></strong><span><?=sprintf('%d / %d',(int)$overallAtt['hit'],(int)$overallAtt['total'])?></span></div><div class="kpi"><small>Mapped Locations</small><strong><?=$mapped?> / <?=$activeCount?></strong></div><div class="kpi"><small>Assessments Missing Location</small><strong><?=$unassigned?></strong></div></div>
<div class="grid"><section class="card"><h2>EPSS Competency Geography</h2><p>Marker size reflects staff assessed. Click a location for detailed indicators.</p><div id="gisMap" class="map"></div><?php if($missing):?><div class="note">Not mapped because coordinates are missing: <?=htmlspecialchars(implode(', ',$missing),ENT_QUOTES,'UTF-8')?>.</div><?php endif;?></section><aside class="card"><h2>Map Rules</h2><p>Workplace coordinates only; CAS does not collect home or real-time GPS locations.</p><div class="note"><strong>Initial coordinates:</strong> the supplied 19 hub points remain Estimated until verified. Administrators can update or add locations without code changes.</div><div class="note"><strong>Scoring:</strong> average competency score is not the same as the percentage of staff reaching the 80% target.</div></aside>
<section class="card full"><h2>Location Comparison</h2><div class="table-wrap"><table class="tbl"><thead><tr><th>Location</th><th>Region</th><th>Assigned Staff</th><th>Assessed</th><th>Average Score</th><th>≥80%</th><th>GIS Status</th><th>Status</th></tr></thead><tbody><?php foreach($metrics as $m):$a=$m['average'];$cl=$a===null?'empty':($a>=80?'good':($a>=70?'mid':($a>=60?'low':'crit')));?><tr><td><a href="?<?=htmlspecialchars(http_build_query(array_merge($query,['location_id'=>$m['id']])),ENT_QUOTES,'UTF-8')?>"><strong><?=htmlspecialchars($m['name'],ENT_QUOTES,'UTF-8')?></strong></a></td><td><?=htmlspecialchars($m['region'],ENT_QUOTES,'UTF-8')?></td><td><?=$m['assigned']?></td><td><?=$m['assessed']?></td><td><span class="pill <?=$cl?>"><?=$a!==null?number_format($a,1).'%':'—'?></span></td><td><?=$m['attainment']!==null?number_format((float)$m['attainment'],1).'%':'—'?><?php if($m['assessed']):?><br><small><?=$m['hit']?>/<?=$m['assessed']?></small><?php endif;?></td><td><?=htmlspecialchars(ucwords(str_replace('_',' ',$m['verification'])),ENT_QUOTES,'UTF-8')?></td><td><?=$m['active']?'Active':'Inactive'?></td></tr><?php endforeach;?></tbody></table></div></section></div></main>
<?php include __DIR__.'/../templates/footer.php';?><script src="<?=htmlspecialchars($leafletJs,ENT_QUOTES,'UTF-8')?>"></script><script nonce="<?=htmlspecialchars(csp_nonce(),ENT_QUOTES,'UTF-8')?>">(function(){const pts=<?=json_encode($points,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,n=document.getElementById('gisMap');if(!n||typeof L!=='object')return;const m=L.map(n,{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m);const b=[];pts.forEach(p=>{const c=p.verification==='verified_exact'?'#2e7d32':(p.verification==='estimated'?'#ef6c00':'#1565c0'),r=Math.max(7,Math.min(19,7+Math.sqrt(Number(p.assessed||0))*2)),q=L.circleMarker([p.lat,p.lon],{radius:r,weight:2,color:c,fillColor:c,fillOpacity:.62}).addTo(m),avg=p.average===null?'—':Number(p.average).toFixed(1)+'%',at=p.attainment===null?'—':Number(p.attainment).toFixed(1)+'%';q.bindPopup('<strong>'+esc(p.name)+'</strong><br>'+esc(p.region)+'<br>'+esc(p.address||'')+'<hr>Assigned staff: '+p.assigned+'<br>Staff assessed: '+p.assessed+'<br>Average score: '+avg+'<br>≥80% target: '+at+'<br>GIS: '+esc(String(p.verification).replaceAll('_',' ')));b.push([p.lat,p.lon]);});b.length?m.fitBounds(b,{padding:[28,28],maxZoom:7}):m.setView([9.1,40.5],5);function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}})();</script></body></html>
