<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/profile_completion.php';
require_once __DIR__ . '/../lib/locations.php';

auth_required(['admin']);
refresh_current_user($pdo);
cas_require_profile_completion($pdo);
ensure_location_schema($pdo);
$locale=ensure_locale(); $t=load_lang($locale); $cfg=get_site_config($pdo); $me=current_user(); $meId=(int)($me['id']??0);
$message=''; $error='';

if ($_SERVER['REQUEST_METHOD']==='POST') {
    csrf_check(); $action=(string)($_POST['action']??'');
    if ($action==='save') {
        $id=max(0,(int)($_POST['location_id']??0)); $before=$id?location_find($pdo,$id):null;
        $payload=[
            'name'=>trim((string)($_POST['name']??'')), 'location_type'=>trim((string)($_POST['location_type']??'hub')),
            'administrative_region'=>trim((string)($_POST['administrative_region']??'')), 'physical_address'=>trim((string)($_POST['physical_address']??'')),
            'latitude'=>trim((string)($_POST['latitude']??'')), 'longitude'=>trim((string)($_POST['longitude']??'')),
            'verification_status'=>trim((string)($_POST['verification_status']??'unverified')), 'notes'=>trim((string)($_POST['notes']??'')),
        ];
        $errors=location_validate_payload($payload); $code=strtoupper(trim((string)($_POST['location_code']??'')));
        if ($code==='') $code=location_generate_code($pdo,$payload['name'],$id?:null);
        if (!preg_match('/^[A-Z0-9][A-Z0-9._-]{1,79}$/',$code)) $errors[]='Location code contains invalid characters.';
        if (!$errors) {
            $q='SELECT id FROM epss_location WHERE (LOWER(name)=LOWER(?) OR location_code=?)'.($id?' AND id<>?':'').' LIMIT 1';
            $p=[$payload['name'],$code]; if($id)$p[]=$id; $s=$pdo->prepare($q); $s->execute($p); if($s->fetchColumn())$errors[]='Another location already uses this name or code.';
        }
        if ($errors) $error=implode(' ',$errors);
        else {
            try {
                $lat=location_coordinate_value($payload['latitude']); $lon=location_coordinate_value($payload['longitude']);
                if ($id) {
                    $s=$pdo->prepare('UPDATE epss_location SET location_code=?,name=?,location_type=?,administrative_region=?,physical_address=?,latitude=?,longitude=?,verification_status=?,notes=?,updated_by=? WHERE id=?');
                    $s->execute([$code,$payload['name'],$payload['location_type'],$payload['administrative_region'],$payload['physical_address']?:null,$lat,$lon,$payload['verification_status'],$payload['notes']?:null,$meId?:null,$id]);
                    location_audit($pdo,$id,'update',$before,location_find($pdo,$id),$meId?:null); $message='Location updated.';
                } else {
                    $s=$pdo->prepare('INSERT INTO epss_location (location_code,name,location_type,administrative_region,physical_address,latitude,longitude,verification_status,is_active,notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,1,?,?,?)');
                    $s->execute([$code,$payload['name'],$payload['location_type'],$payload['administrative_region'],$payload['physical_address']?:null,$lat,$lon,$payload['verification_status'],$payload['notes']?:null,$meId?:null,$meId?:null]);
                    $id=(int)$pdo->lastInsertId(); location_audit($pdo,$id,'create',null,location_find($pdo,$id),$meId?:null); $message='Location added.';
                }
            } catch(Throwable $e){error_log('Location save failed: '.$e->getMessage());$error='Unable to save location.';}
        }
    } elseif ($action==='toggle') {
        $id=max(0,(int)($_POST['location_id']??0)); $before=location_find($pdo,$id);
        if(!$before)$error='Location not found.'; else {$active=(int)$before['is_active']===1?0:1;$pdo->prepare('UPDATE epss_location SET is_active=?,updated_by=? WHERE id=?')->execute([$active,$meId?:null,$id]);location_audit($pdo,$id,$active?'reactivate':'deactivate',$before,location_find($pdo,$id),$meId?:null);$message=$active?'Location reactivated.':'Location deactivated; historical links are retained.';}
    } elseif ($action==='assign') {
        $uid=max(0,(int)($_POST['user_id']??0)); $lid=max(0,(int)($_POST['location_id']??0));
        if(!$uid)$error='Select a user.'; elseif($lid&&!location_is_active($pdo,$lid))$error='Select an active location.'; else {$pdo->prepare('UPDATE users SET location_id=? WHERE id=?')->execute([$lid?:null,$uid]);$message='User duty station updated.';}
    }
}

$editId=max(0,(int)($_GET['edit']??0)); $edit=$editId?location_find($pdo,$editId):null;
$types=location_type_options(); $verify=location_verification_options(); $locations=location_records($pdo,false); $byId=location_map_by_id($pdo,false);
$counts=[]; foreach(($pdo->query('SELECT location_id,COUNT(*) c FROM users WHERE location_id IS NOT NULL GROUP BY location_id')->fetchAll(PDO::FETCH_ASSOC)?:[]) as $r)$counts[(int)$r['location_id']]=(int)$r['c'];
$users=$pdo->query("SELECT id,username,full_name,location_id FROM users WHERE account_status<>'disabled' ORDER BY COALESCE(NULLIF(full_name,''),username)")->fetchAll(PDO::FETCH_ASSOC)?:[];
$points=[];$missing=[];foreach($locations as $l){if((int)$l['is_active']!==1)continue;$lat=location_coordinate_value($l['latitude']);$lon=location_coordinate_value($l['longitude']);if($lat===null||$lon===null){$missing[]=$l['name'];continue;}$points[]=['name'=>$l['name'],'region'=>$l['administrative_region'],'address'=>$l['physical_address'],'lat'=>$lat,'lon'=>$lon,'verification'=>$l['verification_status'],'users'=>$counts[(int)$l['id']]??0];}
$leafletCss='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css'; $leafletJs='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';
?>
<!doctype html><html lang="<?=htmlspecialchars($locale,ENT_QUOTES,'UTF-8')?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EPSS Work Locations & GIS</title>
<link rel="stylesheet" href="<?=asset_url('assets/css/material.css')?>"><link rel="stylesheet" href="<?=asset_url('assets/css/styles.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars($leafletCss,ENT_QUOTES,'UTF-8')?>">
<style nonce="<?=htmlspecialchars(csp_nonce(),ENT_QUOTES,'UTF-8')?>">.loc-page{max-width:1500px;margin:auto;padding:1rem}.loc-head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.loc-head h1{margin:0;color:#10233f}.loc-grid{display:grid;grid-template-columns:5fr 7fr;gap:1rem;margin-top:1rem}.loc-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:1rem}.loc-card h2{margin:0 0 .7rem;color:#0d47a1;font-size:1.05rem}.loc-form{display:grid;grid-template-columns:1fr 1fr;gap:.65rem}.wide{grid-column:1/-1}.loc-map{height:470px;border:1px solid #dce4ed;border-radius:10px}.note{border-left:4px solid #ef6c00;background:#fff8ed;padding:.7rem;margin:.7rem 0 0;font-size:.83rem}.table-wrap{overflow:auto}.loc-table{width:100%;border-collapse:collapse;font-size:.82rem}.loc-table th,.loc-table td{padding:.5rem;border-bottom:1px solid #e7edf4;text-align:left}.loc-table th{background:#f8fafc}.actions{display:flex;gap:.4rem;flex-wrap:wrap}.full{grid-column:1/-1}.assign{display:grid;grid-template-columns:1.4fr 1.2fr auto;gap:.7rem;align-items:end}@media(max-width:950px){.loc-grid{grid-template-columns:1fr}.full{grid-column:auto}.assign{grid-template-columns:1fr}}@media(max-width:620px){.loc-form{grid-template-columns:1fr}.wide{grid-column:auto}.loc-map{height:380px}}</style></head>
<body class="<?=htmlspecialchars(site_body_classes($cfg),ENT_QUOTES,'UTF-8')?>"><?php include __DIR__.'/../templates/header.php'; ?>
<main class="loc-page"><div class="loc-head"><div><h1>EPSS Work Locations & GIS</h1><p>Maintain HQ and hubs used by staff profiles and location analytics. This does not change questionnaire assignment logic.</p></div><div class="actions"><a class="md-button md-outline" href="<?=htmlspecialchars(url_for('admin/analytics_locations.php'),ENT_QUOTES,'UTF-8')?>">Open GIS Analytics</a><?php if($edit):?><a class="md-button md-outline" href="<?=htmlspecialchars(url_for('admin/locations.php'),ENT_QUOTES,'UTF-8')?>">Add New</a><?php endif;?></div></div>
<?php if($message):?><div class="md-alert success"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="md-alert error"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="loc-grid"><section class="loc-card"><h2><?=$edit?'Edit Location':'Add Location'?></h2><form method="post" class="loc-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save"><input type="hidden" name="location_id" value="<?=(int)($edit['id']??0)?>">
<label class="md-field"><span>Name</span><input name="name" required value="<?=htmlspecialchars((string)($edit['name']??''),ENT_QUOTES,'UTF-8')?>"></label><label class="md-field"><span>Internal code</span><input name="location_code" placeholder="Auto-generated if blank" value="<?=htmlspecialchars((string)($edit['location_code']??''),ENT_QUOTES,'UTF-8')?>"></label>
<label class="md-field"><span>Type</span><select name="location_type"><?php $sv=(string)($edit['location_type']??'hub');foreach($types as $v=>$lab):?><option value="<?=$v?>" <?=$sv===$v?'selected':''?>><?=htmlspecialchars($lab,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label class="md-field"><span>Region</span><input name="administrative_region" required value="<?=htmlspecialchars((string)($edit['administrative_region']??''),ENT_QUOTES,'UTF-8')?>"></label>
<label class="md-field wide"><span>Physical address / reference</span><input name="physical_address" value="<?=htmlspecialchars((string)($edit['physical_address']??''),ENT_QUOTES,'UTF-8')?>"></label><label class="md-field"><span>Latitude</span><input name="latitude" inputmode="decimal" value="<?=htmlspecialchars((string)($edit['latitude']??''),ENT_QUOTES,'UTF-8')?>"></label><label class="md-field"><span>Longitude</span><input name="longitude" inputmode="decimal" value="<?=htmlspecialchars((string)($edit['longitude']??''),ENT_QUOTES,'UTF-8')?>"></label>
<label class="md-field wide"><span>GIS verification</span><select name="verification_status"><?php $vv=(string)($edit['verification_status']??'unverified');foreach($verify as $v=>$lab):?><option value="<?=$v?>" <?=$vv===$v?'selected':''?>><?=htmlspecialchars($lab,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label class="md-field wide"><span>Notes</span><textarea name="notes" rows="3"><?=htmlspecialchars((string)($edit['notes']??''),ENT_QUOTES,'UTF-8')?></textarea></label><div class="actions wide"><button class="md-button md-primary">Save</button><?php if($edit):?><a class="md-button md-outline" href="<?=htmlspecialchars(url_for('admin/locations.php'),ENT_QUOTES,'UTF-8')?>">Cancel</a><?php endif;?></div></form><div class="note"><strong>Historical safety:</strong> deactivate old locations instead of deleting them.</div></section>
<section class="loc-card"><h2>EPSS Location Map</h2><div id="locationMasterMap" class="loc-map"></div><div class="note">The supplied 19 hub coordinates are seeded as <strong>Estimated</strong>. HQ remains unpinned until exact coordinates are verified.</div><?php if($missing):?><p class="note">Missing coordinates: <?=htmlspecialchars(implode(', ',$missing),ENT_QUOTES,'UTF-8')?></p><?php endif;?></section>
<section class="loc-card full"><h2>Location Master</h2><div class="table-wrap"><table class="loc-table"><thead><tr><th>Location</th><th>Type</th><th>Region</th><th>Coordinates</th><th>GIS status</th><th>Users</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($locations as $l):$id=(int)$l['id'];$active=(int)$l['is_active']===1;?><tr><td><strong><?=htmlspecialchars($l['name'],ENT_QUOTES,'UTF-8')?></strong><br><small><?=htmlspecialchars($l['location_code'],ENT_QUOTES,'UTF-8')?></small></td><td><?=htmlspecialchars($types[$l['location_type']]??$l['location_type'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($l['administrative_region'],ENT_QUOTES,'UTF-8')?></td><td><?=$l['latitude']!==null?htmlspecialchars($l['latitude'].', '.$l['longitude'],ENT_QUOTES,'UTF-8'):'—'?></td><td><?=htmlspecialchars($verify[$l['verification_status']]??$l['verification_status'],ENT_QUOTES,'UTF-8')?></td><td><?=number_format($counts[$id]??0)?></td><td><?=$active?'Active':'Inactive'?></td><td><div class="actions"><a class="md-button md-outline" href="<?=htmlspecialchars(url_for('admin/locations.php?edit='.$id),ENT_QUOTES,'UTF-8')?>">Edit</a><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="location_id" value="<?=$id?>"><button class="md-button <?=$active?'md-danger':'md-outline'?>"><?=$active?'Deactivate':'Reactivate'?></button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="loc-card full"><h2>Assign User Duty Station</h2><form method="post" class="assign"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assign"><label class="md-field"><span>User</span><select name="user_id" required><option value="">Select user</option><?php foreach($users as $u):$name=trim((string)$u['full_name'])?:$u['username'];$lid=(int)($u['location_id']??0);$current=$lid?(string)($byId[$lid]['name']??'Unknown'):'Not assigned';?><option value="<?=(int)$u['id']?>"><?=htmlspecialchars($name.' (@'.$u['username'].') — '.$current,ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label class="md-field"><span>Work location</span><select name="location_id"><option value="0">Not assigned</option><?php foreach($locations as $l):if((int)$l['is_active']!==1)continue;?><option value="<?=(int)$l['id']?>"><?=htmlspecialchars($l['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><button class="md-button md-primary">Update Assignment</button></form></section></div></main>
<?php include __DIR__.'/../templates/footer.php'; ?><script src="<?=htmlspecialchars($leafletJs,ENT_QUOTES,'UTF-8')?>"></script><script nonce="<?=htmlspecialchars(csp_nonce(),ENT_QUOTES,'UTF-8')?>">(function(){const pts=<?=json_encode($points,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const n=document.getElementById('locationMasterMap');if(!n||typeof L!=='object')return;const m=L.map(n,{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m);const b=[];pts.forEach(p=>{const c=p.verification==='verified_exact'?'#2e7d32':(p.verification==='estimated'?'#ef6c00':'#1565c0');const q=L.circleMarker([p.lat,p.lon],{radius:8,weight:2,color:c,fillColor:c,fillOpacity:.65}).addTo(m);q.bindPopup('<strong>'+esc(p.name)+'</strong><br>'+esc(p.region)+'<br>'+esc(p.address||'')+'<br>GIS: '+esc(String(p.verification).replaceAll('_',' '))+'<br>Assigned users: '+Number(p.users||0));b.push([p.lat,p.lon]);});b.length?m.fitBounds(b,{padding:[24,24],maxZoom:7}):m.setView([9.1,40.5],5);function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}})();</script></body></html>
